"LIBRARIES TO IMPORT"
"================================================================================================================"
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(shinyWidgets)
library(shinythemes)
library(shinyBS)
library(shinyjs)
library(dplyr)
library(tidyverse)
library(readxl)
library(lobstr)
library(data.table)
library(stringr)
library(plotly)
library(ggiraph)
library(ggiraphExtra)
library(leaflet)
library(ggmap)
library(markdown)
library(httr)
library('leaflet.extras')
library(Rblpapi)
library(matrixStats)
library("gridExtra")
library(xts)
library(TTR)
library(dygraphs)
library(compiler)
library(Rblpapi)
library(DT)
library(reshape2)
library(openxlsx)
library(fda)
library(YieldCurve)

ip=gsub(".*? ([[:digit:]])", "\\1", system("ipconfig", intern = TRUE)[grepl("IPv4",system("ipconfig", intern = TRUE))])
print(paste0("http://",ip,":9876/" ))

runApp('Z:/6. Risques Métiers/5. Investissements financiers/Etude Portefeuille Actifs/05 - Shiny App (Test)',host ='10.152.131.36', port=9876)
