fluidRow(column(1, tags$h2(),
         dropdownButton(
           #   box(status = "warning",
           # solidHeader = T,
           # collapsible = T,
           # title = "Risk Factor Inputs",
           #  background = "black",
           #  width=2,
           numericInput("EConv", label = "EConv - Conventional Equity Quantiles", min = 0.001, max = 0.999, value = 0.5, step = 0.05),
           numericInput("FL", label = "FL - Interest Rate Level Quantiles", min = 0.001, max = 0.999, value = 0.5, step = 0.05),
           numericInput("CCorp", label = "CCorp - Corporate Credit Quantiles", min = 0.001, max = 0.999, value = 0.5, step = 0.05),
           numericInput("CSov", label = "CSov - Sovereign Credit Quantiles", min = 0.001, max = 0.999, value = 0.5, step = 0.05),
           numericInput("P", label = "P - Property Quantiles", min = 0.001, max = 0.999, value = 0.5, step = 0.05),
           numericInput("EqVol", label = "EqVol - Equity Volatility Quantiles", min = 0.001, max = 0.999, value = 0.5, step = 0.05),
           numericInput("FVol", label = "FVol - Interest Rate Volatility Quantiles", min = 0.001, max = 0.999, value = 0.5, step = 0.05),
           numericInput("Infl", label = "Inf - Inflation Quantiles", min = 0.001, max = 0.999, value = 0.5, step = 0.05),
           
           circle = TRUE, 
           status = "danger",
           icon = icon("gear"), width = "300px",
           
           tooltip = tooltipOptions(title = "Click to set inputs !"))),
         
        column(1, tags$h2(),
         dropdownButton(
           #   box(status = "warning",
           # solidHeader = T,
           # collapsible = T,
           # title = "Risk Factor Inputs",
           #  background = "black",
           #  width=2,
           numericInput("EConv2", label = "Equity Value (in %)", 
                       min = round(min(spline_data$EConv),2),
                       max = round(max(spline_data$EConv),2), 
                       value = 0, step = 0.005),
           numericInput("FL2", label = "Interest Rate Parallel Shift (in %)", 
                        min = round(min(spline_data$FL),2),
                        max = round(max(spline_data$FL),2), 
                        value = 0, step = 0.005),
           numericInput("CCorp2", label = "CCorp - Corporate Credit Value", 
                        min = round(min(spline_data$CCorp),2),
                        max = round(max(spline_data$CCorp),2), value = 0, step = 0.005),
           numericInput("CSov2", label = "CSov - Sovereign Credit Value", 
                        min = round(min(spline_data$CSov),2),
                        max = round(max(spline_data$CSov),2), value = 0, step = 0.005),
           numericInput("P2", label = "Property Index Return", 
                        min = round(min(spline_data$P),2),
                        max = round(max(spline_data$P),2), value = 0, step = 0.005),
           numericInput("EqVol2", label = "EqVol - Equity Volatility Value", 
                        min = round(min(spline_data$EqVol),2),
                        max = round(max(spline_data$EqVol),2), value = 0, step = 0.005),
           numericInput("FVol2", label = "FVol - Interest Rate Volatility Value", 
                        min = round(min(spline_data$FVol),2),
                        max = round(max(spline_data$FVol),2), value = 0, step = 0.005),
           numericInput("Infl2", label = "Inf - Inflation Value", 
                        min = round(min(spline_data$Infl),2),
                        max = round(max(spline_data$Infl),2), value = 0, step = 0.005),
           
           circle = TRUE, 
           status = "danger",
           icon = icon("gear"), width = "300px",
           
           tooltip = tooltipOptions(title = "Click to set inputs !"))),
         
        column(2, 
         switchInput(
           inputId = "Quantile",
           label = "Calc By Quantile",
           value = T,
           size = "large",
           labelWidth = "80px")), 
         column(8,
                valueBoxOutput("OF_Value"),
                valueBoxOutput("OF_Var_Tot"),
                valueBoxOutput("OF_Variation")))
